# -*- coding: utf-8 -*-
"""kmeans_clustering_task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hlgEoAxuSqvb9ZpZwtistqTnqpSPfQV1

### Note on Data Loading

Previously, the notebook encountered a `FileNotFoundError` because `kmeans_clustering_task.ipynb` was not found and is not a suitable format for `pd.read_csv`.

To allow the rest of the clustering code to run and demonstrate the KMeans algorithm, I have replaced the data loading line with code that generates a synthetic dataset. This synthetic data has 5 features, and the clustering will be performed on features 3 and 4, consistent with your original code `df.iloc[:,[3,4]].values`.

**To use your own data:**
1.  **Upload your data file** (e.g., a `.csv` file) to your Colab environment by clicking the 'Files' icon on the left sidebar and then the 'Upload' button.
2.  **Replace the data generation code** in the next cell with your actual data loading code, e.g., `df = pd.read_csv('your_data_file.csv')`.
"""

from google.colab import drive
drive.mount('/content/drive')

from sklearn.datasets import make_blobs

# Generate synthetic data for demonstration, assuming the original code expected at least 5 columns
# and would use the 3rd and 4th columns (0-indexed 3 and 4) for clustering.
# We create 100 samples with 5 features and 3 centers for illustrative purposes.
X_synth, _ = make_blobs(n_samples=100, n_features=5, centers=3, random_state=42, cluster_std=1.0)
df = pd.DataFrame(X_synth, columns=[f'feature_{i}' for i in range(5)])

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs # Added import


X_synth, _ = make_blobs(n_samples=100, n_features=5, centers=3, random_state=42, cluster_std=1.0)
df = pd.DataFrame(X_synth, columns=[f'feature_{i}' for i in range(5)]) # Replaced pd.read_csv

x = df.iloc[:,[3,4]].values

model = KMeans(n_clusters=5,random_state=42)
groups = model.fit_predict(x)

plt.figure(figsize=(8,6))
plt.scatter(x[:,0],x[:,1], c= groups, cmap='rainbow')

plt.scatter(model.cluster_centers_[:,0], model.cluster_centers_[:,1], c='black',label='centers')

plt.title("customer groups")
plt.xlabel("annual income")
plt.ylabel("spoending score")
plt.show()